spring:
  profiles:
    active:
    - dev
  application:
    name: service-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
---
spring:
  profiles: dev
server:
  port: 8767
  
---
spring:
  profiles: dev
server:
  port: 8768  