
spring:
  application:
    name: service-hi
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
---
spring:
  profiles: dev
server:
  port: 8763
   
---
spring:
  profiles: uat
server:
  port: 8764
      
  